import { ClerkProvider } from '@clerk/nextjs';
import './global.css';
import { frFR, enUS } from '@clerk/localizations';
import { getLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
export const metadata = {
  title: 'Welcome to elyope-admin',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <ClerkProvider localization={locale === 'fr' ? frFR : enUS}>
      <html lang={locale}>
        <body className="bg-el-grey-200 text-el-grey-800 text-14">
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
