import { Sidemenu } from '@/components/shared';
import './global.css';

export const metadata = {
  title: 'Welcome to veterinarian',
  description: 'Generated by create-nx-workspace',
};

const menuItems = [
  { href: '/', label: 'Accueil' },
  { href: '/examens', label: 'Examens' },
  { href: '#', label: 'Animaux' },
  { href: '#', label: 'Messagerie', badge: 1 },
  { href: '/design', label: 'Design' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-el-grey-200 text-el-grey-800 text-14">
        <div className="flex gap-1 ">
          <Sidemenu menuItems={menuItems} />
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
