import { ClerkProvider } from '@clerk/nextjs';
import './global.css';

export const metadata = {
  title: 'Welcome to veterinarian',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-el-grey-200 text-el-grey-800 text-14">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
