export { default as Animaux } from './Animaux';
export { default as Examens } from './Examens';
export { default as ExamensIcon } from './Examens';
export { default as Messagerie } from './Messagerie';
export { default as Profile } from './Profile';
export { default as Search } from './search';
export { default as TrashIcon } from './Trash';
export { default as PencilIcon } from './Pencil';
export { default as DuplicateIcon } from './Duplicate';
export { default as ArrowLeftIcon } from './ArrowLeft';
export { default as SearchIcon } from './search';
export { default as MessagerieIcon } from './Messagerie';
export { default as ProfileIcon } from './Profile';
export { default as AnimauxIcon } from './Animaux';
export { BriefCaseIcon } from './BriefCase';
export { UserIcon } from './UserIcon';
export { default as NoDataIcon } from './NoData';
export { default as LoadingSpinner } from './LoadingSpinner';
export { default as ExclamationCircleIcon } from './ExclamationCircle';
